# Apache config for docker container
<VirtualHost *:80>
	ServerAdmin martin.molema@nhlstenden.com
    ServerName localhost

	DocumentRoot /var/www/student
    DirectoryIndex index.php index.html

	<Directory /var/www/student>
		Options -Indexes
		options MultiViews FollowSymLinks
		AllowOverride All
		Require all granted

	</Directory>

	# ErrorLog ${APACHE_LOG_DIR}/error.log
	ErrorLog /dev/stderr

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	# CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
