name: php-tutorial
services:
    webserver-php-tutorial:
        build: ./webserver
        networks:
            - webdevelopment
        environment:
            - DB_SERVER=${DB_SERVER}
            - DB_USER=${DB_ROOT_USER}
            - DB_PASSWORD=${DB_ROOT_PASSWORD}
            - PHP_IDE_CONFIG=serverName=localhost
        volumes:
            - ./websites:/var/www/student
        depends_on:
            - mysql-php-tutorial
        ports:
            - "80:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql-php-tutorial:
        image: mariadb:latest
        networks:
            - webdevelopment
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin
        networks:
            - webdevelopment
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql-php-tutorial
        depends_on:
            - webserver-php-tutorial
            - mysql-php-tutorial
volumes:
    mysqldata: {}

networks:
    webdevelopment:
        driver: bridge
